
package com.htong.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WebServiceClassService", targetNamespace = "http://ws.htong.com/", wsdlLocation = "http://10.67.106.160:8090/ws?wsdl")
public class WebServiceClassService
    extends Service
{

    private final static URL WEBSERVICECLASSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.htong.ws.WebServiceClassService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.htong.ws.WebServiceClassService.class.getResource(".");
            url = new URL(baseUrl, "http://10.67.106.160:8090/ws?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.67.106.160:8090/ws?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WEBSERVICECLASSSERVICE_WSDL_LOCATION = url;
    }

    public WebServiceClassService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceClassService() {
        super(WEBSERVICECLASSSERVICE_WSDL_LOCATION, new QName("http://ws.htong.com/", "WebServiceClassService"));
    }

    /**
     * 
     * @return
     *     returns WebServiceClass
     */
    @WebEndpoint(name = "WebServiceClassPort")
    public WebServiceClass getWebServiceClassPort() {
        return super.getPort(new QName("http://ws.htong.com/", "WebServiceClassPort"), WebServiceClass.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceClass
     */
    @WebEndpoint(name = "WebServiceClassPort")
    public WebServiceClass getWebServiceClassPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.htong.com/", "WebServiceClassPort"), WebServiceClass.class, features);
    }

}
