
package com.htong.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WebServiceClass", targetNamespace = "http://ws.htong.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceClass {


    /**
     * 
     * @return
     *     returns java.util.List<com.htong.ws.DtuStatusModel>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDTUStatus", targetNamespace = "http://ws.htong.com/", className = "com.htong.ws.GetDTUStatus")
    @ResponseWrapper(localName = "getDTUStatusResponse", targetNamespace = "http://ws.htong.com/", className = "com.htong.ws.GetDTUStatusResponse")
    public List<DtuStatusModel> getDTUStatus();

}
